### ISSUE TITLE
Get Banner Data and Importing Said Data to MongoDB

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#107]
# Description of Issue
As a Developer, I need access to the relevant data of professors, classes, students, etc., in order to set up the database so the system has access for the relevant data.

# Acceptance Criteria
- [ ] Get Banner Data from EIT
- [x] Create Scripts to import data to MongoDB
- [ ] Verify scripts

**Comment by thelenzr** [comment]
EIT will not allow us to access banner data because of FERPA. (See reasoning below)

"EIT cannot provide Institute data or access to Institute data for academic purposes.  Even though EIT maintains the data subsystems, the data is controlled by the policies and restrictions of the individual offices that maintain it.  Access to non-directory educational record data is regulated by FERPA and it has many restrictions on the distribution of data to third parties."

Closing this issue as our plan will shift as we move forward. A new issue with different acceptance criteria will be created when we have a solution. The progress I made will remain in the branch for now.
