### ISSUE TITLE
Project Documentation Review

### ISSUE THREAD

**Issue by rileyma** [CompileIO/compile.io#179]
# Description of Issue
As a stakeholder, I'd like to have a well documented project so that if this project went open-source, developers would have little to no trouble with the on-boarding process. 

# Acceptance Criteria
- [x] Review Code and address areas lacking/needing Documentation
- [ ] Address additional Documentation concerns that may not be directly code-related (how to set-up environment, required software download instructions, design philosophy, etc.)

**Comment by pastorsj** [comment]
@rileyma @footezo @joshpal97 We would like to see the following added as part of the documentation for this project.
- [ ] Add the actual poster and get rid of the mock poster. Also, instead of adding a powerpoint file, leave it as an image file, but feel free to put the powerpoint in the google drive folder if that hasn't happened already.
- [ ] Documentation of the CI/CD process. We are confused about how this process actually works, considering all of the bash scripts are commented out.
- [ ] API documentation. We would like documentation of each endpoint, so in case a developer would want to refactor/update this work in the future, they would not cause any breaking changes.
- [ ] Update how to run the code locally. I was unable to run the code locally, but maybe that was due to the environment I was running in. Also, this is probably one of the most important pieces of information when first working with this codebase, so this information should probably end up in the README file.

**Comment by rileyma** [comment]
@pastorsj Thank you for the feedback. I've converted your comment into an issue for next sprint.
